import os
from dotenv import load_dotenv
import anthropic
import sys
from functions.get_files_info import get_files_from_wd
from functions.get_file_contents import get_contents
from functions.write_file_content import write_file
from functions.run_python import run_python

load_dotenv()
_api_key = os.getenv("ANTHROPIC_API_KEY")
client=anthropic.Anthropic(api_key=_api_key)
tools=[
     {
        "name": "get_files_from_wd",
        "description": "List files in a directory",
        "input_schema": {
            "type": "object",
            "properties": {
                "directory": {"type": "string", "description": "subdirectory to list"}
            },
            "required": []
        }
    },
 {
        "name": "get_contents",
        "description": "It reads the contents of the file",
        "input_schema": {
            "type": "object",
            "properties": {
                "file_path": {"type": "string", "description": "path of the file"}
            },
            "required": ["file_path"]
        }
    },


     {
        "name": "write_file",
        "description": "It writes the contents of the file",
        "input_schema": {
            "type": "object",
            "properties": {
                "file_path": {"type": "string", "description": "path of the file"},
                "content": {"type": "string", "description": "The answer generated by LLM"}
            },
            "required": ["file_path", "content"]
        }
    },
    {
        "name": "run_python",
        "description": "It Runs the python code",
        "input_schema": {
            "type": "object",
            "properties": {
                "file_path": {"type": "string", "description": "path of the file"},
                "args": {"type": "array", "description": "The arguments given by user"},
            },
            "required": ["file_path"]
        }
    },
    
]

WORKING_DIR = "calculator"
def execute_tool(name,input):
    if name == "get_files_from_wd":
        return get_files_from_wd(WORKING_DIR, input.get("directory"))
    elif name == "get_contents":
        return get_contents(WORKING_DIR, input["file_path"])
    elif name == "write_file":
        return write_file(WORKING_DIR, input["file_path"], input["content"])
    elif name == "run_python":
        return run_python(WORKING_DIR, input["file_path"], input.get("args", []))

def main():
    conversation_history=[]
    prompt=sys.argv[1]
   
    MODEL="claude-sonnet-4-6"
    conversation_history.append({"role": "user", "content": prompt})    
    while True:
        response = client.messages.create(model=MODEL, max_tokens=4096,tools=tools,messages=conversation_history,system="You are a Python coding agent. You only answer Python related questions. Your working directory is 'calculator'. Use the available tools to complete the task.")
        conversation_history.append({"role": "assistant", "content": response.content})

        if response.stop_reason == "end_turn":
            for block in response.content:
                if block.type == "text":
                    print(block.text)
            break
        if response.stop_reason == "tool_use":
            tool_results = []
            for block in response.content:
                if block.type == "tool_use":
                    result = execute_tool(block.name, block.input)
                    tool_results.append({
                        "type": "tool_result",
                        "tool_use_id": block.id,
                        "content": result
                    })
            conversation_history.append({"role": "user", "content": tool_results})
        
        
   
if __name__ == "__main__":
    main()
    #print(get_files_from_wd("calculator"))

